version: 2
jobs:
  build:
#    branches:
#      only: Assignment7
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build War
          command: |
            cd ./webapp/recipie_management_system
            ./mvnw clean install
            cd target
            ls -al
            cd ../../..
      - run:
          name: Zip Artifact
          command: |
            echo "Build number ${CIRCLE_BUILD_NUM}"
            pwd
            find . -name appspec.yml
            ls -al
            mkdir -p codedeploy_artifact
            find ./infrastructure/aws/codedeploy/ -name *.sh
            cp infrastructure/aws/codedeploy/*.sh .
            find . -name *.yml
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/recipie_management_system/target/ROOT.war *.sh *.yml
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Install pip
          command: |
            sudo apt-get update
            sudo apt-get install python3
            python3 --version
            sudo apt install python3-pip
            pip3 --version
      - run:
          name: AWS CLI Install
          command: |
            sudo pip3 install awscli
            which aws
      - run:
          name: Upload to s3
          command: |
            echo "s3"
            cd codedeploy_artifact
            aws s3 cp csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${AWS_CODE_DEPLOY_BUCKET}
            echo "Uploaded to s3"
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "CodeDeploy API call"
            aws deploy register-application-revision --region ${AWS_REGION} --application-name csye6225-webapp \
            --s3-location bucket=${AWS_CODE_DEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip
            echo "***************************************************************************************************"
            aws deploy list-application-revisions --region ${AWS_REGION} --application-name csye6225-webapp \
            --s-3-bucket ${AWS_CODE_DEPLOY_BUCKET} --deployed exclude
            echo "***************************************************************************************************"
            deploymentId=$(aws deploy create-deployment --region ${AWS_REGION} \
            --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name csye6225-webapp-deployment \
            --s3-location bucket=${AWS_CODE_DEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE,DEPLOYMENT_STOP_ON_ALARM,DEPLOYMENT_STOP_ON_REQUEST)
            echo "$deploymentId"